let products = [
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 250,
        "location": "Lagos",
        "image": "images/product-math.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1002,
        "title": "English",
        "description": "English is spoken in every country, and by this it is not our native language but we have the best set of teachers to put you through.",
        "price": 230,
        "location": "Valletta",
        "image": "images/product-english.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1003,
        "title": "Basketball",
        "description": "We are willing to teach you the basics of the basketball game, to help you go pro.",
        "price": 150,
        "location": "Lagos",
        "image": "images/product-bball.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1004,
        "title": "Football",
        "description":  "We are willing to teach you the basics of the football game, to help you go pro.",
        "price": 120,
        "location": "Swieqi",
        "image": "images/product-ball.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1005,
        "title": "Music",
        "description":"Music brings a different vibe to the body and soul,come enjoy and explore the world of music and various instruments.",
        "price": 110,
        "location": "St-Julian",
        "image": "images/product-music.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1006,
        "title": "Farming",
        "description": "Farmers help us a lot in our economy today, we would put your child through the process of farming and importance of helping the community.",
        "price": 100,
        "location": "Ikoyi",
        "image": "images/product-farm.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1007,
        "title": "Geography",
        "description": "Geography is the study of the Earth's physical features and environment including the impact of human activity on these factors and vice versa.",
        "price": 90,
        "location": "Valletta",
        "image": "images/product-geo.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1008,
        "title": "French",
        "description": "Learning extra languages can be very helpful, french is spoken at most ceremonies, we would help you learn.",
        "price": 190,
        "location": "Swieqi",
        "image": "images/product-education.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1009,
        "title": "Swimming",
        "description": "Swimming helps build your cardio, helps ease stress and relax, we have top trainers ready to help put your child through.",
        "price": 95,
        "location": "St-Julian",
        "image": "images/product-swim.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1010,
        "title": "Karate",
        "description": "The art of karate is a very lovely skill to harness, Let's put you through from beginner to expert level and you can compete anywhere.",
        "price": 145,
        "location": "Ikoyi",
        "image": "images/product-karate.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
]